Traceback (most recent call last):
  File "/usr/local/bin/luigid", line 11, in <module>
    sys.exit(luigid())
  File "/usr/local/lib/python3.6/dist-packages/luigi/cmdline.py", line 35, in luigid
    logdir=opts.logdir, unix_socket=opts.unix_socket)
  File "/usr/local/lib/python3.6/dist-packages/luigi/process.py", line 127, in daemonize
    cmd(api_port=api_port, address=address, unix_socket=unix_socket)
  File "/usr/local/lib/python3.6/dist-packages/luigi/server.py", line 314, in run
    scheduler = Scheduler()
  File "/usr/local/lib/python3.6/dist-packages/luigi/scheduler.py", line 712, in __init__
    from luigi import db_task_history  # Needs sqlalchemy, thus imported here
  File "/usr/local/lib/python3.6/dist-packages/luigi/db_task_history.py", line 48, in <module>
    import sqlalchemy
ModuleNotFoundError: No module named 'sqlalchemy'
Traceback (most recent call last):
  File "/usr/local/bin/luigid", line 11, in <module>
    sys.exit(luigid())
  File "/usr/local/lib/python3.6/dist-packages/luigi/cmdline.py", line 35, in luigid
    logdir=opts.logdir, unix_socket=opts.unix_socket)
  File "/usr/local/lib/python3.6/dist-packages/luigi/process.py", line 127, in daemonize
    cmd(api_port=api_port, address=address, unix_socket=unix_socket)
  File "/usr/local/lib/python3.6/dist-packages/luigi/server.py", line 314, in run
    scheduler = Scheduler()
  File "/usr/local/lib/python3.6/dist-packages/luigi/scheduler.py", line 712, in __init__
    from luigi import db_task_history  # Needs sqlalchemy, thus imported here
  File "/usr/local/lib/python3.6/dist-packages/luigi/db_task_history.py", line 48, in <module>
    import sqlalchemy
ModuleNotFoundError: No module named 'sqlalchemy'
